name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ R√©cup√©rer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Installer l‚Äôoutil CLI de Render
      - name: Install Render CLI
        run: |
          curl -L https://cli.render.com/install | bash
          echo "$HOME/.render/bin" >> $GITHUB_PATH

      # 3Ô∏è‚É£ D√©ployer sur Render avec la cl√© secr√®te
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploy service srv-d5095e7pm1nc73c6sgng --wait

      # 4Ô∏è‚É£ Notification de succ√®s
      - name: Deployment success
        if: success()
        run: echo "üöÄ D√©ploiement Render r√©ussi ‚Äî WebOps Lab est en ligne"

      # 5Ô∏è‚É£ Notification d‚Äô√©chec
      - name: Deployment failed
        if: failure()
        run: echo "‚ùå D√©ploiement Render √©chou√© ‚Äî v√©rifie les logs GitHub Actions"

