name: Deploy to Render

on:
  push:
    branches:
      - main  # se déclenche à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer l’outil CLI de Render
      - name: Install Render CLI
        run: |
          curl -L https://cli.render.com/install | bash

      # 3️⃣ Déployer sur Render avec la clé secrète
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # clé que tu as ajoutée
        run: |
          render deploy service srv-d5095e7pm1nc73c6sgng --wait
